// import { Geist, Geist_Mono } from "next/font/google";
import NavbarServer from "@/Components/NavbarServer";
import "./globals.css";
import { AuthProvider } from "@/app/AuthProvider";
import Link from "next/link";

//className={`${geistSans.variable} ${geistMono.variable} antialiased`}

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Blog Viewer App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en" data-theme="light">
      
      
        <body >
        <main>
        <nav className="bg-gray-300">
          <NavbarServer></NavbarServer>
            {/* <div>
              <Link href="/" className="bg-gray-400 font-bold px-5 py-2 text-xl rounded-lg">BlogViewer</Link>
              <ul>
                <li><Link href="/">Home</Link></li>
                <li><Link href="/">Profile</Link></li>
              </ul>
            </div> */}
          </nav>
        
         {children}
         </main>
        </body>
      </html>
    </AuthProvider>
  );
}
